name: push-env
on:
  push:
    branches:
      - main
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Process
      run: echo "Setting environment variables!"
      env:
        REACT_APP_EMAILJS_SERVICE: ${{ secrets.EMAILJS_SERVICE }}
        REACT_APP_EMAILJS_TEMPLATE: ${{ secrets.EMAILJS_TEMPLATE }}
        REACT_APP_EMAILJS_USER: ${{ secrets.EMAILJS_USER }}
